name: Windows

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: runs-on=${{ github.run_id }}/image=windows11-full-x64/family=m7i
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check current dir and env variables
        run: |
          dir .
          echo $env:USERNAME
          echo $env:RUNS_ON_RUNNER_NAME
      - name: Logs
        run: |
          Get-Content -Path "C:\runs-on\output.log"
      - name: Users
        run: |
          Get-LocalUser | Format-Table -AutoSize Name,Enabled,PasswordLastSet
